# Specify the base image
FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app

# Specify working directory
WORKDIR /home/node/app


COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]